# The Great Confursion
# (c) 2019 Jessica Hart
# Powered by git-wiki

# (string) Title of your wiki
title: Confursion
# (string) Description of your wiki
description: Knowledgebase for the anthropic shift, and the humans who went furry
# (boolean) Enable/disable wiki page list in sidebar
show_wiki_pages: false
# (integer) Maximum number of wiki page to shown in sidebar
show_wiki_pages_limit: 10
# (boolean) Enable/disable blog feature
blog_feature: false
# (boolean) Enable/disable wiki posts list in sidebar (needs blog_feature enabled)
show_wiki_posts: false
# (integer) Maximum number of wiki posts to shown in sidebar
show_wiki_posts_limit: 10
# from jekyll (read jekyll doc)
paginate: 5
paginate_path: "/blog/page:num"
permalink: /blog/posts/:year/:month/:day/:title:output_ext
# (boolean) Enable/disable download buttons in sidebar
show_downloads: false
# (string) Specify branch rendered by gitpages allowing wiki tool buttons to work
git_branch: "master"
# (string) Url of logo image, it can be full, absolute or relative.
logo_url: "/confursionpaw-512.png"
# (string) The UA-XXXXX-Y code from google analytic to enable GA on your wiki
google_analytics: UA-71040338-4
# (string) folder where wiki pages are stored, it's needed for tool buttons
wiki_folder: wiki
# (boolean) if you're using github wiki as submodule then this config
# must be enabled to allow tool buttons to work properly
use_github_wiki: false
# (boolean) Enable "Edit with Prose.io" button in tools, it's a 3rd party
# service to edit github markdown pages easily
use_prose_io: false
# Select search_engine component from:
# - js: it uses a built in javascript component that uses generated js object
# - js_rss: it uses a built in javascript component that uses generated  sitemap_full.xml to search inside your wiki with lunr library (slow and experimental)
# - github : it uses internal github repository search
# - google : it uses cse search bar, you need to configure google_cse_token
#
search_engine : "js"
# Setting google custom search engine for google
# cse search bar (https://cse.google.it/cse/)
google_cse_token: 

#
# Jekyll configurations
#

# You can customize it changing default layout for all pages
# More info: https://jekyllrb.com/docs/configuration/
#
# git-wiki includes some internal themes that you can choose
# check _layouts folder
#
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  wiki:
    permalink: /:path
    output: true

defaults:
# - 
#    scope:
#      path: "wiki"
#    values:
#      permalink: /:path/:basename
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "git-wiki-post"
 -
    scope:
      path: blog
    values:
      layout: "git-wiki-blog"
sass:
    style: compressed
plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions


#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_before_toc : 
inc_after_toc : "confursion/infobox.html"
inc_before_content : 
inc_after_content : 
inc_before_footer : 
inc_after_footer : 
inc_before_head : 
inc_after_head : "confursion/head.html"
inc_before_meta : 
inc_after_meta : 
inc_before_scripts : 
inc_after_scripts : 
inc_before_styles : 
inc_after_styles : 
inc_before_header : 
inc_after_header : "confursion/sidebar.html"
inc_before_tail : 
inc_after_tail : 
inc_before_tools : 
inc_after_tools : 

inc_before_page_list : 
inc_after_page_list : 
inc_before_post_list :
inc_after_post_list :

prose:
  rooturl: '_wiki'
  siteurl: https://confursion.hokora.page
  media: 'img'
  metadata:
    _wiki:
      - name: 'title'
        field:
          element: 'text'
          label: 'title'
      - name: 'notoc'
        field:
          element: 'checkbox'
          label: 'No TOC'
          help: 'Check to remove table of contents'
      - name: 'noedit'
        field:
          element: 'checkbox'
          label: 'No Edit'
          help: 'Check to remove edit link'
      - name: 'infobox'
        field:
          element: 'checkbox'
          label: 'Infobox'
          help: 'Includes infobox'
      - name: 'ititle'
        field:
          element: 'text'
          label: 'Infobox Title'
          placeholder: 'Display Name'
      - name: 'image'
        field:
          element: 'text'
          label: 'Infobox Image'
          help: 'Note: this will not upload the image for you'
          placeholder: '/img/url_to_image.png'
      - name: 'caption'
        field:
          element: 'text'
          label: 'Infobox Caption'
          placeholder: 'Description of the image'
      - name: 'list'
        field:
          element: 'textarea'
          label: 'Infobox Table'
          help: 'Markdown definition list'
          placeholder: | 
            Thing One
            
            : Foo


            Thing Two

            : Bar
